# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Write Time Done, Alight with Heart -- an Alva Chien's Blog
email: alvachien@163.com
description: >- # this means to ignore newlines until "baseurl:"
  Copyright by Alva Chien, 2020.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alvachien.github.io" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %H:%M"

  skin: "dark"
  
  # generate social links in footer
  social_links:
    github:  alvachien
    # devto: jekyll
    # dribbble: jekyll
    facebook: alva.chien
    flickr:   alvachien
    # instagram: jekyll
    linkedin: alvachien
    # pinterest: jekyll

# Paginate
paginate: 10
paginate_path: '/page:num/'
pagination:
  previous: "&larr; Previous"
  next: "Next &rarr;"

# Upload images
defaults:
  - scope:
      path: "assets/uploads"
    values:
      image: true

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  html_to_native: true
  syntax_highlighter: rouge

theme: minima
encoding: utf-8
permalink: /:year/:month/:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
