title: 码一地闲言，蕴一段岁月 | Write Time Down, Alongside with Heart
author: Alva Chien
email: alvachien@163.com
description: © 2004 - 2026, Alva Chien.
baseurl: ""
url: "https://alvachien.github.io"
timezone: Asia/Shanghai

theme: minimal-mistakes-jekyll

locale: zh-CN
name: Alva Chien

comments:
  provider: false

atom_feed:
  path: atom.xml

search: true

permalink: /:year/:month/:day/:title
paginate: 20
paginate_path: /page:num/

excerpt_length: 50

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

encoding: utf-8

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache