title: 码一地闲言，蕴一段岁月
author: Alva Chien
email: alvachien@163.com
description: >-
  © 2004 - 2026, Alva Chien.
baseurl: ""
url: "https://alvachien.github.io"
timezone: Asia/Shanghai

navbar-links:
  About Me: "about"

social-network-links:
  email: "alvachien@163.com"
  github: alvachien
  facebook: alva.chien
  flickr: alvachien
  linkedin: alvachien

rss-description: Alva Chien's Blog

share-links-active:
  twitter: false
  facebook: true
  linkedin: true

permalink: /:year/:month/:day/:title
paginate: 20

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: beautiful-jekyll-theme
encoding: utf-8

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-feed

