title: 码一地闲言，蕴一段岁月 | Write Time Down, Alongside with Heart
author: Alva Chien
email: alvachien@163.com
description: © 2004 - 2026, Alva Chien.
baseurl: ""
url: "https://alvachien.github.io"
locale: zh-CN
name: Alva Chien
encoding: utf-8
words_per_minute         : 200
enable_copy_code_button  : true

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"

comments:
  provider: false

atom_feed:
  hide: true

search                   : true # true, false (default)
search_full_content      : true # true, false (default)

# Outputting
permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai

paginate: 20
paginate_path: /page:num/

excerpt_length: 50
date_format: "%Y-%m-%d"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

footer:
  links:
    - label: "Linked in"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/alvaachien"
      rel: "me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alvachien"
      rel: "me"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/alvachien"
      rel: "me"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      show_date: true
      related: true

include:
  - _pages

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development